### ISSUE TITLE
bug: loading placeholders wrong colors

### ISSUE THREAD

**Issue by platon-rov** [SAP/theming-base-content#12]
## Description

Wrong colors of loading placeholders.

**Fiori**, **Horizon** (default light themes)

`--sapContent_Placeholderloading_Background`
In wiki: `#E0E0E0`
In library: `#CCCCCC`

`--sapContent_Placeholderloading_Gradient`
In wiki: `linear-gradient(to right, #e0e0e0 0%, #e0e0e0 35%, #d3d3d3 50%, #e0e0e0 65%, #e0e0e0 100%)`
in library: `linear-gradient(to right, #cccccc 0%, #cccccc 20%, #999999 50%, #cccccc 80%, #cccccc 100%)`

**Comment by droshev** [comment]
we sort it out. the ticket can be closed
