### ISSUE TITLE
bug: emphasized button color in evening horizon

### ISSUE THREAD

**Issue by tal-si** [SAP/theming-base-content#14]
The current color defined for emphasized  button in evening horizon theme is `#eaecee`.

This color produces contrast ratio of 3.85:1 which is not WCAG compliant.

> https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_horizon_dark/css_variables.css

The expected color is `#ffffff` as described in the official Fiori specification.

> https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2650676574#id-14Button(Horizon)-EmphasizedButton

**Comment by dominikschreiber** [comment]
Hi @tal-si! With theming-base-content 11.1.49, `@sapButton_Emphasized_TextColor` is #ffffff in Evening Horizon, just as specified.
