### ISSUE TITLE
Corrupt 11.1.48 tarball

### ISSUE THREAD

**Issue by ronsantiagoSAP** [SAP/theming-base-content#15]
Hi Team,

We recently tried to upgrade to @sap-theming/theming-base-content@11.1.48 and noticed the following error during the build. We ended up using the previous patch version 11.1.47 instead in order to unblock our pipeline. Is it possible that the [11.1.48 tarball file](https://registry.npmjs.org/@sap-theming/theming-base-content/-/theming-base-content-11.1.48.tgz) is really corrupt?

16:04:32 INFO - npm WARN tarball tarball data for @sap-theming/theming-base-content@11.1.48 (sha512-Q2rMoEN+6tjnfbhlQ2a+WybhAWj/0RuhWUb3vSzI/iwCkGPGtz3k8HhtU1jtmAPjRCiJQSEmiE2HMv3Av/7Y7Q==) seems to be corrupted. Trying one more time.

16:04:41 INFO - npm WARN tarball tarball data for @sap-theming/theming-base-content@11.1.48 (sha512-Q2rMoEN+6tjnfbhlQ2a+WybhAWj/0RuhWUb3vSzI/iwCkGPGtz3k8HhtU1jtmAPjRCiJQSEmiE2HMv3Av/7Y7Q==) seems to be corrupted. Trying one more time.

16:04:52 INFO -

16:04:52 ERROR - code EINTEGRITY

16:04:52 ERROR - Verification failed while extracting @sap-theming/theming-base-content@11.1.48:

16:04:52 ERROR - Verification failed while extracting @sap-theming/theming-base-content@11.1.48:

16:04:52 ERROR - sha512-Q2rMoEN+6tjnfbhlQ2a+WybhAWj/0RuhWUb3vSzI/iwCkGPGtz3k8HhtU1jtmAPjRCiJQSEmiE2HMv3Av/7Y7Q== integrity checksum failed when using sha512: wanted sha512-Q2rMoEN+6tjnfbhlQ2a+WybhAWj/0RuhWUb3vSzI/iwCkGPGtz3k8HhtU1jtmAPjRCiJQSEmiE2HMv3Av/7Y7Q== but got sha512-3B+tB85OXzpCk26WOkeZBnP3c4fEwAR0giKC4UBYYOmokDxSMXn3tfiCkg6Y06I2C7aOyQDVB7Uns6arKmaZWQ==. (15471810 bytes)

**Comment by dominikschreiber** [comment]
Hi @ronsantiagoSAP, and sorry for the late reply. This should be fixed with [11.1.49](https://www.npmjs.com/package/@sap-theming/theming-base-content/v/11.1.49).
