### ISSUE TITLE
Icons not centered vertically 

### ISSUE THREAD

**Issue by nbblum** [SAP/theming-base-content#16]
The .sap-icon--arrow-right and arrow-left and some other icons are not vertically centered which results to problems when trying to align them with other ui elements
![image](https://github.com/SAP/fundamental-styles/assets/85098790/e59048a2-d9fb-4b52-8ff0-f11be8acfcc9)

here is a basic example:
https://plnkr.co/edit/kAUolEPWMg1lRU4S?open=lib%2Fscript.js&preview
![image](https://github.com/SAP/fundamental-styles/assets/85098790/bdcdc57a-869b-401a-8d28-14174c0aadff)

This could be a duplicate of https://github.com/SAP/fundamental-styles/issues/4532 I'm not sure which repository is the correct one for this issue

**Comment by dominikschreiber** [comment]
Hi @nbblum! Thank you for bringing that up. I'll take this observation to our icon designers and get back to you.

**Comment by nbblum** [comment]
@dominikschreiber any updates regarding this? Can we somehow help?

**Comment by nbblum** [comment]
With the lastest version (theming-base-content@11.5.0) the arrows are now aligned
![image](https://github.com/SAP/theming-base-content/assets/85098790/68f51b7e-fe4f-47d0-a43b-2c702608c32d)

https://plnkr.co/edit/kAUolEPWMg1lRU4S

**Comment by dominikschreiber** [comment]
Hey @nbblum, sorry for my late answer… I'm still on parental leave. Glad that you figured out that 11.5.0 fixed the issue yourselves 😀. All the best!
