### ISSUE TITLE
Feedback icon is missing in 'SAP-icons' font

### ISSUE THREAD

**Issue by marynaKhromova** [SAP/theming-base-content#3]
We would like to use the **feedback** icon from [openui5](https://openui5.hana.ondemand.com/test-resources/sap/m/demokit/iconExplorer/webapp/index.html#/overview/SAP-icons/?tab=grid&icon=add-product&search=feedback) but seems like it's missing in `SAP-icons` font when I check all icons on [Fundamental Library Styles](https://sap.github.io/fundamental-styles/components/icon.html) page.

**Comment by eugen-roth** [comment]
Hi Maryna,

sorry for the late reply!
I think your issue is solved by now, as we shipped SAP-Icons v.4.9 within the last theming-base-content delivery. 
The feedback-icon was added in SAP-Icons v.4.5.

kind regards
Eugen
