### ISSUE TITLE
Missing 72-Italic.woff2

### ISSUE THREAD

**Issue by lenient** [SAP/theming-base-content#4]
I cannot see the 72-Italic.woff2 in the following folder,
https://github.com/SAP/theming-base-content/tree/master/content/Base/baseLib/baseTheme/fonts

**Comment by eugen-roth** [comment]
Hi,

it is not intended to ship 72-Italic font yet.
As there are only a few places where italic style is needed, this is accomplished using CSS-style.

kind regards, Eugen

**Comment by eugen-roth** [comment]
Hi,

font **72-Italic** is now available within theming-base-content version 11.1.32.

kind regards, Eugen
