### ISSUE TITLE
Can I delete some Unnecessary font-face declaration in content/Base/baseLib/sap_belize_plus/css_variables.css

### ISSUE THREAD

**Issue by Vita-Meow** [SAP/theming-base-content#8]

**Comment by dominikschreiber** [comment]
css_variables.css of sap_belize_plus contain `@font-face` definitions that get removed for all other themes. This might be caused by the scoping of sap_belize into sap_belize_plus. I'll investigate in the SAP-internal upstream project.

**Comment by dominikschreiber** [comment]
We've found and fixed the root cause of this issue, indeed in our SAP-internal tooling. The css_variables of sap_belize_plus will not contain `@font-face` definitions starting with the next open source release (which is 11.1.35).

**Comment by Vita-Meow** [comment]
> We've found and fixed the root cause of this issue, indeed in our SAP-internal tooling. The css_variables of sap_belize_plus will not contain `@font-face` definitions starting with the next open source release (which is 11.1.35).

Thank your for your quick response! That's awesome!
