### ISSUE TITLE
Invalid css in css_variables.css

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/theming-base-content#9]
Hi colleagues,

in my opinion, the CSS Variable `--sapThemeMetaData-Base-baseLib` in the `css_variables.css` is invalid in all themes (I guess there are some quotes missing around the json data):
https://github.com/SAP/theming-base-content/blob/72f3764285e3c11577680dec0f7a1a7c61f8d755/content/Base/baseLib/sap_fiori_3/css_variables.css#L9

The [W3C CSS Validator Service](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Funpkg.com%2F%40sap-theming%2Ftheming-base-content%4011.1.37%2Fcontent%2FBase%2FbaseLib%2Fsap_fiori_3%2Fcss_variables.css&profile=css3svg&usermedium=all&warning=1&vextwarning=&lang=en) is also reporting errors for this file.

This is e.g. causing errors in the production build of `create-react-app` when trying to import the CSS Variable files directly.

cc @vladitasev

**Comment by dominikschreiber** [comment]
As far as I can tell, [values of CSS custom properties](https://drafts.csswg.org/css-variables/#defining-variables) have to be a `<declaration-value>`:

> The &lt;declaration-value> production matches any sequence of one or more tokens, so long as the sequence does not contain [&lt;bad-string-token>](https://drafts.csswg.org/css-syntax-3/#typedef-bad-string-token), [&lt;bad-url-token>](https://drafts.csswg.org/css-syntax-3/#typedef-bad-url-token), unmatched [&lt;)-token>](https://drafts.csswg.org/css-syntax-3/#tokendef-close-paren), [&lt;\]-token>](https://drafts.csswg.org/css-syntax-3/#tokendef-close-square), or [&lt;}-token>](https://drafts.csswg.org/css-syntax-3/#tokendef-close-curly), or top-level [&lt;semicolon-token>](https://drafts.csswg.org/css-syntax-3/#typedef-semicolon-token) tokens or [&lt;delim-token>](https://drafts.csswg.org/css-syntax-3/#typedef-delim-token) tokens with a value of "!". It represents the entirety of what a valid declaration can have as its value.

So while unquoted JSON is most certainly an uncommon CSS custom property value, in my opinion it is *still a valid one*.

This goes in line with the behavior of all major browsers, which parse the CSS just fine and the property can be accessed just as intended:

```js
JSON.parse(getComputedStyle(document.documentElement).getPropertyValue('--sapThemeMetaData-Base-baseLib'))
```

See [this repro](https://codepen.io/dominikschreiber/pen/ZEvXqME?editors=0110) to convince yourself.

The `--sapThemeMetaData*` parameters are not intended to be used in CSS directly, but rather to convey information to JavaScript frameworks about the currently active SAP- or custom-theme.

**With that, the conclusion is that the W3C CSS Validator Service and create-react-app have a bug in their CSS parsing algorithm. Please file an issue there.**
